//! Rendering of generated `hardware-configuration.nix`, `configuration.nix`,
//! and `flake.nix`.

#![allow(
  clippy::expect_used,
  reason = "writes to in-memory String cannot fail"
)]

use std::fmt::Write as _;

/// A single import line for the generated hardware config. Each entry is a
/// literal Nix expression, e.g. `(modulesPath + "/profiles/qemu-guest.nix")`.
pub type NixExpr = String;

/// Escape `s` so that embedding it between double quotes in Nix source is
/// safe. Handles the four escape sequences Nix recognizes inside double-
/// quoted strings: `\"`, `\\`, `\$` (to neutralize antiquotation), and
/// control characters via `\n`, `\r`, `\t`. Any other byte is passed
/// through unchanged.
///
/// This is the only correct way to embed dynamic data (mount points,
/// device paths, labels, hostnames) into generated Nix — mountinfo can
/// contain spaces, quotes, backslashes, and after octal decoding even
/// newlines.
#[must_use]
pub fn nix_escape(s: &str) -> String {
  let mut out = String::with_capacity(s.len());
  let mut chars = s.chars().peekable();
  while let Some(c) = chars.next() {
    match c {
      '"' => out.push_str("\\\""),
      '\\' => out.push_str("\\\\"),
      '\n' => out.push_str("\\n"),
      '\r' => out.push_str("\\r"),
      '\t' => out.push_str("\\t"),
      '$' if chars.peek() == Some(&'{') => out.push_str("\\$"),
      other => out.push(other),
    }
  }
  out
}

#[cfg(test)]
mod escape_tests {
  use super::*;

  #[test]
  fn passes_through_simple_paths() {
    assert_eq!(nix_escape("/dev/sda1"), "/dev/sda1");
    assert_eq!(nix_escape("@home"), "@home");
    assert_eq!(nix_escape("UUID=abc-123"), "UUID=abc-123");
  }

  #[test]
  fn escapes_double_quotes_and_backslashes() {
    assert_eq!(nix_escape(r#"/mnt/foo"bar"#), r#"/mnt/foo\"bar"#);
    assert_eq!(nix_escape(r"back\slash"), r"back\\slash");
  }

  #[test]
  fn escapes_control_characters_after_octal_decode() {
    assert_eq!(nix_escape("a\nb"), "a\\nb");
    assert_eq!(nix_escape("x\ty"), "x\\ty");
    assert_eq!(nix_escape("r\rn"), "r\\rn");
  }

  #[test]
  fn neutralizes_antiquotation() {
    assert_eq!(nix_escape("${evil}"), "\\${evil}");
    // A bare dollar outside `${...}` is not special.
    assert_eq!(nix_escape("cost $5"), "cost $5");
  }
}

/// Everything the hardware-configuration renderer needs.
#[derive(Debug, Default, Clone)]
pub struct HardwareReport {
  pub imports:                      Vec<NixExpr>,
  pub initrd_available_kernel_mods: Vec<String>,
  pub initrd_kernel_modules:        Vec<String>,
  pub kernel_modules:               Vec<String>,
  pub extra_module_packages:        Vec<NixExpr>,
  /// Pre-formatted single-line attribute assignments, e.g.
  /// `virtualisation.virtualbox.guest.enable = true;`. These are appended to
  /// the bottom of the generated file verbatim.
  pub attrs:                        Vec<String>,
  /// Pre-rendered `fileSystems."X" = { ... };` blocks, concatenated. Empty
  /// if `no_filesystems` is true.
  pub file_systems:                 String,
  /// Each entry is a bare Nix attrset like `{ device = "/dev/..."; }`.
  pub swap_devices:                 Vec<NixExpr>,
  pub no_filesystems:               bool,
}

#[derive(Debug, Clone, Copy)]
pub enum BootLoader {
  SystemdBoot,
  Extlinux,
  /// systemd-nspawn container — no bootloader entry at all.
  Nspawn,
  Grub,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kernel {
  Lts,
  Latest,
}

#[derive(Debug, Clone)]
pub struct ConfigurationCtx {
  pub state_version:         String,
  pub boot_loader:           BootLoader,
  pub kernel:                Kernel,
  /// Extra text (e.g. from a desktop manager module) spliced into the file.
  /// Indented by two spaces, one blank line before.
  pub desktop_configuration: Option<String>,
}

#[derive(Debug, Clone)]
pub struct FlakeCtx {
  pub hostname: String,
}

/// Render hardware-configuration.nix from a [`HardwareReport`].
#[must_use]
pub fn render_hardware_config(report: &HardwareReport) -> String {
  let mut out = String::new();
  out.push_str(
    "# Do not modify this file!  It was generated by 'nh os \
     generate-config'\n# and may be overwritten by future invocations.  \
     Please make changes\n# to /etc/nixos/configuration.nix instead.\n{ \
     config, lib, pkgs, modulesPath, ... }:\n\n{\n",
  );

  out.push_str("  imports = ");
  write_multiline_expr_list(&mut out, "  ", &report.imports);
  out.push_str(";\n\n");

  writeln!(
    out,
    "  boot.initrd.availableKernelModules = {};",
    fmt_inline_string_list(&report.initrd_available_kernel_mods)
  )
  .expect("write to String is infallible");
  writeln!(
    out,
    "  boot.initrd.kernelModules = {};",
    fmt_inline_string_list(&report.initrd_kernel_modules)
  )
  .expect("write to String is infallible");
  writeln!(
    out,
    "  boot.kernelModules = {};",
    fmt_inline_string_list(&report.kernel_modules)
  )
  .expect("write to String is infallible");
  writeln!(
    out,
    "  boot.extraModulePackages = {};",
    fmt_inline_expr_list(&report.extra_module_packages)
  )
  .expect("write to String is infallible");

  if !report.no_filesystems {
    out.push('\n');
    out.push_str(&report.file_systems);
    out.push_str("  swapDevices = ");
    write_multiline_expr_list(&mut out, "  ", &report.swap_devices);
    out.push_str(";\n");
  }

  if !report.attrs.is_empty() {
    out.push('\n');
    for attr in &report.attrs {
      writeln!(out, "  {attr}").expect("write to String is infallible");
    }
  }

  out.push_str("}\n");
  out
}

/// Render configuration.nix.
#[must_use]
pub fn render_configuration(ctx: &ConfigurationCtx) -> String {
  let mut out = String::new();
  out.push_str(
    "# Edit this configuration file to define what should be installed on\n\
     # your system. Help is available in the configuration.nix(5) man page, \
     on\n\
     # https://search.nixos.org/options and in the NixOS manual \
     (`nixos-help`).\n\
     \n\
     { config, lib, pkgs, ... }:\n\
     \n\
     {\n\
     \x20\x20imports = [\n\
     \x20\x20\x20\x20# Include the results of the hardware scan.\n\
     \x20\x20\x20\x20./hardware-configuration.nix\n\
     \x20\x20];\n\
     \n",
  );

  out.push_str(&render_boot_loader(ctx.boot_loader));

  if ctx.kernel == Kernel::Latest {
    out.push_str("\n  # Use latest kernel.\n");
    out.push_str("  boot.kernelPackages = pkgs.linuxPackages_latest;\n");
  }

  out.push_str(
    "\n  # networking.hostName = \"nixos\"; # Define your hostname.\n\n",
  );
  out.push_str(
    "  # Configure network connections interactively with nmcli or nmtui.\n",
  );
  out.push_str("  networking.networkmanager.enable = true;\n\n");
  out.push_str("  # Set your time zone.\n");
  out.push_str("  # time.timeZone = \"Europe/Amsterdam\";\n\n");
  out.push_str("  # Configure network proxy if necessary\n");
  out.push_str(
    "  # networking.proxy.default = \"http://user:password@proxy:port/\";\n",
  );
  out.push_str(
    "  # networking.proxy.noProxy = \
     \"127.0.0.1,localhost,internal.domain\";\n\n",
  );
  out.push_str("  # Select internationalisation properties.\n");
  out.push_str("  # i18n.defaultLocale = \"en_US.UTF-8\";\n");
  out.push_str("  # console = {\n");
  out.push_str("  #   font = \"Lat2-Terminus16\";\n");
  out.push_str("  #   keyMap = \"us\";\n");
  out.push_str("  #   useXkbConfig = true; # use xkb.options in tty.\n");
  out.push_str("  # };\n");

  if let Some(desktop) = &ctx.desktop_configuration {
    out.push('\n');
    for line in desktop.lines() {
      writeln!(out, "  {line}").expect("write to String is infallible");
    }
  }

  out.push_str(
    "\n  # Enable CUPS to print documents.\n\
     \x20\x20# services.printing.enable = true;\n\
     \n  # Enable sound.\n\
     \x20\x20# services.pulseaudio.enable = true;\n\
     \x20\x20# OR\n\
     \x20\x20# services.pipewire = {\n\
     \x20\x20#   enable = true;\n\
     \x20\x20#   pulse.enable = true;\n\
     \x20\x20# };\n\
     \n  # Enable touchpad support (enabled default in most desktopManager).\n\
     \x20\x20# services.libinput.enable = true;\n\
     \n  # Define a user account. Don't forget to set a password with \
     'passwd'.\n\
     \x20\x20# users.users.alice = {\n\
     \x20\x20#   isNormalUser = true;\n\
     \x20\x20#   extraGroups = [ \"wheel\" ]; # Enable 'sudo' for the user.\n\
     \x20\x20#   packages = with pkgs; [\n\
     \x20\x20#     tree\n\
     \x20\x20#   ];\n\
     \x20\x20# };\n\
     \n  # programs.firefox.enable = true;\n\
     \n  # List packages installed in system profile.\n\
     \x20\x20# You can use https://search.nixos.org/ to find more packages \
     (and options).\n\
     \x20\x20# environment.systemPackages = with pkgs; [\n\
     \x20\x20#   vim # Do not forget to add an editor to edit \
     configuration.nix! The Nano editor is also installed by default.\n\
     \x20\x20#   wget\n\
     \x20\x20# ];\n\
     \n  # Some programs need SUID wrappers, can be configured further or \
     are\n\
     \x20\x20# started in user sessions.\n\
     \x20\x20# programs.mtr.enable = true;\n\
     \x20\x20# programs.gnupg.agent = {\n\
     \x20\x20#   enable = true;\n\
     \x20\x20#   enableSSHSupport = true;\n\
     \x20\x20# };\n\
     \n  # List services that you want to enable:\n\
     \n  # Enable the OpenSSH daemon.\n\
     \x20\x20# services.openssh.enable = true;\n\
     \n  # Open ports in the firewall.\n\
     \x20\x20# networking.firewall.allowedTCPPorts = [ ... ];\n\
     \x20\x20# networking.firewall.allowedUDPPorts = [ ... ];\n\
     \x20\x20# Or disable the firewall altogether.\n\
     \x20\x20# networking.firewall.enable = false;\n\
     \n  # Copy the NixOS configuration file and link it from the resulting \
     system\n\
     \x20\x20# (/run/current-system/configuration.nix). This is useful in \
     case you\n\
     \x20\x20# accidentally delete configuration.nix.\n\
     \x20\x20# system.copySystemConfiguration = true;\n\
     \n  # This option defines the first version of NixOS you have installed \
     on this particular machine,\n\
     \x20\x20# and is used to maintain compatibility with application data \
     (e.g. databases) created on older NixOS versions.\n\
     \x20\x20#\n\
     \x20\x20# Most users should NEVER change this value after the initial \
     install, for any reason,\n\
     \x20\x20# even if you've upgraded your system to a new NixOS release.\n\
     \x20\x20#\n\
     \x20\x20# This value does NOT affect the Nixpkgs version your packages \
     and OS are pulled from,\n\
     \x20\x20# so changing it will NOT upgrade your system - see \
     https://nixos.org/manual/nixos/stable/#sec-upgrading for how\n\
     \x20\x20# to actually do that.\n\
     \x20\x20#\n\
     \x20\x20# This value being lower than the current NixOS release does \
     NOT mean your system is\n\
     \x20\x20# out of date, out of support, or vulnerable.\n\
     \x20\x20#\n\
     \x20\x20# Do NOT change this value unless you have manually inspected \
     all the changes it would make to your configuration,\n\
     \x20\x20# and migrated your data accordingly.\n\
     \x20\x20#\n\
     \x20\x20# For more information, see `man configuration.nix` or \
     https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .\n",
  );
  writeln!(
    out,
    "  system.stateVersion = \"{v}\"; # Did you read the comment?",
    v = ctx.state_version
  )
  .expect("write to String is infallible");
  out.push_str("\n}\n");
  out
}

#[must_use]
pub fn render_flake(ctx: &FlakeCtx) -> String {
  // Always quote the hostname segment so that names containing dots (e.g.
  // `host.example`), quotes, or other non-identifier characters produce a
  // single configuration attribute rather than a nested attrset.
  format!(
    "{{\n\
     \x20\x20inputs = {{\n\
     \x20\x20\x20\x20# This is pointing to an unstable release.\n\
     \x20\x20\x20\x20# If you prefer a stable release instead, you can \
     change this to the latest number shown here: https://nixos.org/download\n\
     \x20\x20\x20\x20# e.g. nixos-25.05\n\
     \x20\x20\x20\x20# Use `nix flake update` to update the flake to the \
     latest revision of the chosen release channel.\n\
     \x20\x20\x20\x20nixpkgs.url = \"github:NixOS/nixpkgs/nixos-unstable\";\n\
     \x20\x20}};\n\
     \x20\x20outputs = inputs@{{ self, nixpkgs, ... }}: {{\n\
     \x20\x20\x20\x20nixosConfigurations.\"{hostname}\" = \
     nixpkgs.lib.nixosSystem {{\n\
     \x20\x20\x20\x20\x20\x20modules = [ ./configuration.nix ];\n\
     \x20\x20\x20\x20}};\n\
     \x20\x20}};\n\
     }}\n",
    hostname = nix_escape(&ctx.hostname),
  )
}

fn render_boot_loader(loader: BootLoader) -> String {
  match loader {
    BootLoader::SystemdBoot => {
      "  # Use the systemd-boot EFI boot loader.\n  \
       boot.loader.systemd-boot.enable = true;\n  \
       boot.loader.efi.canTouchEfiVariables = true;\n"
        .to_owned()
    },
    BootLoader::Extlinux => {
      "  # Use the extlinux boot loader. (NixOS wants to enable GRUB by \
       default)\n  boot.loader.grub.enable = false;\n  # Enables the \
       generation of /boot/extlinux/extlinux.conf\n  \
       boot.loader.generic-extlinux-compatible.enable = true;\n"
        .to_owned()
    },
    BootLoader::Nspawn => String::new(),
    BootLoader::Grub => {
      "  # Use the GRUB 2 boot loader.\n  boot.loader.grub.enable = true;\n  # \
       boot.loader.grub.efiSupport = true;\n  # \
       boot.loader.grub.efiInstallAsRemovable = true;\n  # \
       boot.loader.efi.efiSysMountPoint = \"/boot/efi\";\n  # Define on which \
       hard drive you want to install Grub.\n  # boot.loader.grub.device = \
       \"/dev/sda\"; # or \"nodev\" for efi only\n"
        .to_owned()
    },
  }
}

fn fmt_inline_string_list(items: &[String]) -> String {
  if items.is_empty() {
    return "[ ]".to_owned();
  }
  let mut out = String::from("[");
  for item in items {
    out.push_str(" \"");
    out.push_str(&nix_escape(item));
    out.push('"');
  }
  out.push_str(" ]");
  out
}

fn fmt_inline_expr_list(items: &[NixExpr]) -> String {
  if items.is_empty() {
    return "[ ]".to_owned();
  }
  let mut out = String::from("[");
  for item in items {
    out.push(' ');
    out.push_str(item);
  }
  out.push_str(" ]");
  out
}

fn write_multiline_expr_list(
  out: &mut String,
  indent: &str,
  items: &[NixExpr],
) {
  if items.is_empty() {
    out.push_str("[ ]");
    return;
  }
  out.push_str("[\n");
  for item in items {
    out.push_str(indent);
    out.push_str("  ");
    out.push_str(item);
    out.push('\n');
  }
  out.push_str(indent);
  out.push(']');
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn hardware_config_minimal() {
    let report = HardwareReport::default();
    let out = render_hardware_config(&report);
    assert!(out.contains("generated by 'nh os generate-config'"));
    assert!(out.contains("imports = [ ];"));
    assert!(out.contains("boot.initrd.availableKernelModules = [ ];"));
    assert!(out.contains("boot.extraModulePackages = [ ];"));
    // no-filesystems default is false; swap is emitted even when empty.
    assert!(out.contains("swapDevices = [ ];"));
  }

  #[test]
  fn hardware_config_no_filesystems_omits_block() {
    let report = HardwareReport {
      no_filesystems: true,
      file_systems: "/* should not appear */".to_owned(),
      ..Default::default()
    };
    let out = render_hardware_config(&report);
    assert!(!out.contains("should not appear"));
    assert!(!out.contains("swapDevices"));
  }

  #[test]
  fn hardware_config_with_imports_modules_attrs() {
    let report = HardwareReport {
      imports: vec!["(modulesPath + \"/profiles/qemu-guest.nix\")".to_owned()],
      initrd_available_kernel_mods: vec![
        "xhci_pci".to_owned(),
        "ahci".to_owned(),
      ],
      kernel_modules: vec!["kvm-intel".to_owned()],
      attrs: vec!["hardware.cpu.intel.updateMicrocode = true;".to_owned()],
      file_systems: "  fileSystems.\"/\" = { device = \"/dev/sda1\"; fsType = \
                     \"ext4\"; };\n"
        .to_owned(),
      swap_devices: vec!["{ device = \"/dev/sda2\"; }".to_owned()],
      ..Default::default()
    };
    let out = render_hardware_config(&report);
    assert!(out.contains("(modulesPath + \"/profiles/qemu-guest.nix\")"));
    assert!(out.contains(
      "boot.initrd.availableKernelModules = [ \"xhci_pci\" \"ahci\" ];"
    ));
    assert!(out.contains("boot.kernelModules = [ \"kvm-intel\" ];"));
    assert!(out.contains("fileSystems.\"/\""));
    assert!(out.contains("{ device = \"/dev/sda2\"; }"));
    assert!(out.contains("hardware.cpu.intel.updateMicrocode = true;"));
  }

  #[test]
  fn configuration_boot_loader_variants() {
    let base = ConfigurationCtx {
      state_version:         "24.11".to_owned(),
      boot_loader:           BootLoader::SystemdBoot,
      kernel:                Kernel::Lts,
      desktop_configuration: None,
    };
    let efi = render_configuration(&base);
    assert!(efi.contains("systemd-boot.enable = true"));
    assert!(efi.contains("system.stateVersion = \"24.11\""));
    assert!(!efi.contains("linuxPackages_latest"));

    let grub = render_configuration(&ConfigurationCtx {
      boot_loader: BootLoader::Grub,
      ..base.clone()
    });
    assert!(grub.contains("boot.loader.grub.enable = true"));

    let extlinux = render_configuration(&ConfigurationCtx {
      boot_loader: BootLoader::Extlinux,
      ..base.clone()
    });
    assert!(extlinux.contains("generic-extlinux-compatible.enable = true"));

    let nspawn = render_configuration(&ConfigurationCtx {
      boot_loader: BootLoader::Nspawn,
      ..base
    });
    assert!(!nspawn.contains("boot.loader"));
  }

  #[test]
  fn configuration_latest_kernel_line() {
    let out = render_configuration(&ConfigurationCtx {
      state_version:         "25.05".to_owned(),
      boot_loader:           BootLoader::SystemdBoot,
      kernel:                Kernel::Latest,
      desktop_configuration: None,
    });
    assert!(out.contains("boot.kernelPackages = pkgs.linuxPackages_latest;"));
  }

  #[test]
  fn flake_uses_hostname() {
    let out = render_flake(&FlakeCtx {
      hostname: "laptop".to_owned(),
    });
    assert!(out.contains("nixosConfigurations.\"laptop\" ="));
    assert!(out.contains("./configuration.nix"));
  }

  #[test]
  fn flake_hostname_with_dot_stays_single_config() {
    let out = render_flake(&FlakeCtx {
      hostname: "host.example".to_owned(),
    });
    // The name must end up as one quoted attr-path segment, not split.
    assert!(out.contains("nixosConfigurations.\"host.example\" ="));
    assert!(!out.contains("nixosConfigurations.host.example ="));
  }

  #[test]
  fn flake_hostname_with_quote_is_escaped() {
    let out = render_flake(&FlakeCtx {
      hostname: "evil\"host".to_owned(),
    });
    assert!(out.contains("nixosConfigurations.\"evil\\\"host\" ="));
  }

  #[test]
  fn inline_string_list_empty_and_populated() {
    assert_eq!(fmt_inline_string_list(&[]), "[ ]");
    assert_eq!(
      fmt_inline_string_list(&["a".to_owned(), "b".to_owned()]),
      "[ \"a\" \"b\" ]"
    );
  }
}
